apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "backend.fullname" . }}
  namespace: {{ .Values.namespaceOverride }}
  labels:
    app: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      {{- if and .Values.serviceAccount (eq .Values.serviceAccount.create true) }}
        serviceAccountName: {{ include "backend.serviceAccountName" . }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            - name: JIRA_URL
              valueFrom:
                secretKeyRef:
                  name: jira-secret
                  key: url
            - name: JIRA_USER
              valueFrom:
                secretKeyRef:
                  name: jira-secret
                  key: user
            - name: JIRA_API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: jira-secret
                  key: token
            - name: JIRA_PROJECT_KEY
              valueFrom:
                secretKeyRef:
                  name: jira-secret
                  key: projectKey
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: openai-key
                  key: api-key 
            - name: PROMETHEUS_URL
              value: "https://prometheus.horizonrelevance.com"       
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
