apiVersion: v1
kind: Service
metadata:
  name: {{ include "frontend.fullname" . }}-service
  namespace: {{ .Values.namespaceOverride }}
  labels:
    app: {{ .Chart.Name }}
spec:
  selector:
    app: {{ .Chart.Name }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
  type: {{ .Values.service.type }}
