apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: loki-data
  namespace: observability-horizon-relevance
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi  # adjust size as needed
  storageClassName: gp3  # or gp2 depending on your EKS setup
