[[servers]]
host = "ldap.jumpcloud.com"
port = 636
use_ssl = true
start_tls = false
ssl_skip_verify = false

bind_dn = "uid=ankur.kashyap,ou=Users,o=6817d9a0d50cd4b1b5b81ba7,dc=jumpcloud,dc=com"
bind_password = "${LDAP_BIND_PASSWORD}"

search_filter = "(uid=%s)"
search_base_dns = ["ou=Users,o=6817d9a0d50cd4b1b5b81ba7,dc=jumpcloud,dc=com"]

group_search_base_dns = ["ou=Users,o=6817d9a0d50cd4b1b5b81ba7,dc=jumpcloud,dc=com"]

[servers.attributes]
name = "givenName"
surname = "sn"
username = "uid"
email = "mail"
member_of = "memberOf"

[[servers.group_mappings]]
group_dn = "*"
org_role = "Admin"
grafana_admin = true
